#!/usr/bin/env bash
# check-commits.sh
#
# Validates that commit messages in a PR follow the Conventional Commits format.
# The allowed commit types are read from repo-config.json in the repository root.
#
# What are Conventional Commits?
# --------------------------------
# A standard format for commit messages:
#   type(optional-scope): short description
#
# Examples:
#   feat: add nginx deployment
#   fix(ingress): correct hostname typo
#   docs: update README prerequisites
#   chore(ci): add yamllint workflow
#
# Why use this?
# - Makes the Git history readable and searchable
# - Enables automated changelog generation
# - Makes code reviews easier (reviewers know what kind of change it is)
#
# Usage:
#   git log origin/main..HEAD --format="%s" | ./scripts/check-commits.sh
#   git log origin/main..HEAD --format="%s" | ./scripts/check-commits.sh /path/to/repo-config.json
#
# Exit code 0 = all commits are valid
# Exit code 1 = one or more commits have invalid format

set -euo pipefail

# ---- configuration -----------------------------------------------------------

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="${1:-${REPO_ROOT}/repo-config.json}"

# ---- dependency check --------------------------------------------------------

if ! command -v jq &>/dev/null; then
  echo "ERROR: jq is required but not installed."
  echo "       Install it with: brew install jq  (macOS)"
  echo "                        apt install jq   (Ubuntu/Debian)"
  exit 1
fi

if [ ! -f "${CONFIG_FILE}" ]; then
  echo "ERROR: Config file not found: ${CONFIG_FILE}"
  exit 1
fi

# ---- build allowed-types regex from repo-config.json -------------------------

# jq reads the keys of .conventionalCommits and joins them with |
# Example output: "break|feat|fix|refactor|docs|chore|ci"
ALLOWED_TYPES=$(jq -r '.conventionalCommits | keys[]' "${CONFIG_FILE}" | paste -sd '|' -)

if [ -z "${ALLOWED_TYPES}" ]; then
  echo "ERROR: No conventional commit types found in ${CONFIG_FILE}"
  exit 1
fi

# Build the full regex pattern:
#   ^(type1|type2)(\(scope\))?(!)?: non-empty description
# The (!) part allows breaking-change marker: feat!: description
PATTERN="^(${ALLOWED_TYPES})(\([^)]+\))?(!)?: .+"

echo "Checking commit messages against repo-config.json"
echo "Allowed types: ${ALLOWED_TYPES//|/, }"
echo "Pattern:       ${PATTERN}"
echo ""

# ---- validate each commit message from stdin ---------------------------------

TOTAL=0
PASSED=0
FAILED=0

while IFS= read -r commit_msg; do
  # Skip empty lines
  [ -z "${commit_msg}" ] && continue

  # Skip merge commits (they are auto-generated by GitHub and follow a different format)
  if echo "${commit_msg}" | grep -qE "^Merge (pull request|branch) "; then
    echo "  SKIP (merge commit): ${commit_msg}"
    continue
  fi

  TOTAL=$((TOTAL + 1))

  if echo "${commit_msg}" | grep -qE "${PATTERN}"; then
    echo "  PASS: ${commit_msg}"
    PASSED=$((PASSED + 1))
  else
    echo "  FAIL: ${commit_msg}"
    echo "        Expected format: type(scope): description"
    echo "        Example:         feat(web): update index.html content"
    echo "        Allowed types:   ${ALLOWED_TYPES//|/, }"
    FAILED=$((FAILED + 1))
  fi
done

# ---- summary -----------------------------------------------------------------

echo ""
echo "Results: ${PASSED}/${TOTAL} commit messages passed"

if [ "${TOTAL}" -eq 0 ]; then
  echo "WARNING: No commit messages to validate (PR may have no new commits)"
  exit 0
fi

if [ "${FAILED}" -gt 0 ]; then
  echo ""
  echo "Fix the failing commits with:"
  echo "  git rebase -i origin/main"
  echo "  # then change 'pick' to 'reword' for the failing commits"
  exit 1
fi

exit 0
